# Generated by Django 4.2 on 2026-09-30 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(help_text='Tabla o modelo afectado (ej. Vehiculo, Item)', max_length=50)),
                ('id_entidad', models.PositiveIntegerField(help_text='ID del registro modificado')),
                ('accion', models.CharField(help_text='CREAR, MODIFICAR, ELIMINAR, etc.', max_length=50)),
                ('detalle', models.JSONField(blank=True, help_text='Snapshot o campos modificados', null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Cambio',
                'verbose_name_plural': 'Historial de Cambios',
                'db_table': 'historial_cambios',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('Auto', 'Auto'), ('Moto', 'Moto'), ('Camioneta', 'Camioneta')], default='Auto', max_length=10)),
                ('chapa', models.TextField()),
                ('motivo_ingreso', models.CharField(choices=[('Revisión General', 'Revision General'), ('Mantenimiento', 'Mantenimiento'), ('Reparación', 'Reparacion'), ('Instalación', 'Instalacion'), ('Otro', 'Otro')], default='Revisión General', max_length=60)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Recibido', 'Recibido'), ('En Espera', 'En Espera'), ('En Diagnóstico', 'En Diagnostico'), ('Pendiente de Aprobación', 'Pendiente Aprobacion'), ('Esperando Repuestos', 'Esperando Repuestos'), ('En Reparación', 'En Reparacion'), ('Listo para Retiro', 'Listo Para Retiro'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Recibido', max_length=60)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='taller.marca')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'db_table': 'Vehiculos',
            },
        ),
    ]
