# Generated by Django 4.2 on 2026-09-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(choices=[('Repuesto de Auto', 'Repuesto Auto'), ('Repuesto de Moto', 'Repuesto Moto'), ('Accesorio', 'Accesorio'), ('Herramienta', 'Herramienta'), ('Otro', 'Otro')], default='Repuesto de Auto', max_length=30)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=0, default=0, help_text='Precio Unitario (PYG)', max_digits=12)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Item de Inventario',
                'verbose_name_plural': 'Items de Inventario',
                'db_table': 'items',
            },
        ),
    ]
